### ISSUE TITLE
いいところ診断の結果に優しさを追加したい

### ISSUE THREAD

**Issue by choco2005** [choco2005/2020assessment#1]
以下の結果を追加したい

'{userName}のいいところは優しさです。あなたの優しい雰囲気や立ち振舞に多くの人が癒やされています。'

**Comment by zepOCaml** [comment]
以下の結果を追加したい

'{userName}のいいところは優しさです。あなたの優しい雰囲気や立ち振舞に多くの人が癒やされています。'

**Comment by choco2005** [comment]
#1 に対する対応を行いました

**Comment by choco2005** [comment]
403de9e で対応されました
